### ISSUE TITLE
Add a screenshot to the readme

### ISSUE THREAD

**Issue by joshka** [BenLeadbetter/shellaga#15]
We use https://github.com/charmbracelet/vhs to create these in Ratatui

I'd caution against storing the image directly in your repo though as it tends to cause your repo to get bloated over time.
VHS has a publish command which is useful.

**Comment by BenLeadbetter** [comment]
Thanks for the tip. I ended up going with [asciinema](https://asciinema.org/), just because it's a tool I'm familiar with.
